### ISSUE TITLE
XDG Spec isn't followed correctly for xsession directories

### ISSUE THREAD

**Issue by taigrr** [FyshOS/fin#15]
According to the XDG spec: ([here](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html))
1. `XDG_DATA_HOME` takes precedence
2. but if it's not set, it should be assumed to be `$HOME/.local/share`
3. Additionally, `XDG_DATA_DIRS` contains system-wide data which should be taken into account at a lower precedence. 
4. If empty, assume it is `/usr/local/share/:/usr/share/`

Currently, the code is backwards, checking the `XDG_DATA_DIRS` variable first, with a couple of fallbacks. `XDG_DATA_HOME` should be used first, with `XDG_DATA_DIRS` as a fallback.

The reason this distinction is important: As it is right now, a non-root user is unable to customize their `xsessions` list, as on any normal system with `XDG_DATA_DIRS` set, user config files will not be read.

**Comment by Jacalz** [comment]
I just want to say that you don't necessarily need to create an issue just to open a PR.
It's fine to just open a PR if you want to do so.

**Comment by taigrr** [comment]
Thanks @Jacalz , I'll take that going forward but there was more context here in some Slack messages.

**Comment by andydotxyz** [comment]
Thanks for resolving this @taigrr
