### ISSUE TITLE
Using fin on archlinux with i3 breaks PulseAudio

### ISSUE THREAD

**Issue by taigrr** [FyshOS/fin#5]
When running `amixer` within a terminal emulator inside of i3 (launched with the .xinitrc option), the following is printed to the screen:

```
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5111:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5599:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib control.c:1481:(snd_ctl_open_noupdate) Invalid CTL sysdefault
cannot open mixer: No such file or directory
```
Running `startx` , everything operates as expected.

**Comment by taigrr** [comment]
I believe this is related to environment variables not being set correctly. 

I attempted to change the .xinit command from `...bash --login...` to `startx` and it doesn't load in the `.xinitrc`, so I'm willing to bet that `$HOME` isn't setting properly, and possibly other things as well. Going to continue investigating.

**Comment by taigrr** [comment]
Modifying my `.xinitrc` from `i3` to `dbus-launch i3` allowed me to get `dunst` up and running again, still working on PulseAudio.

**Comment by taigrr** [comment]
Ok, feel free to close this.

`startx` apparently handles a lot of this default stuff for you, and replacing `startx` with `bash --login` removes all of the helpers.

PulseAudio wasn't functioning because it wasn't launched. Normally it automatically launches after running `startx`.

Adding `pulseaudio --start` to my `.xinitrc` made everything work again.

I will leave it open, as hopefully you might consider adding something about this to the README/docs, but no code change is required.

**Comment by andydotxyz** [comment]
I don't think that Fin (and it's docs) extend to managing .xinitrc content.
If you did follow some steps that I have forgotten we wrote please respond here so we can fix - otherwise I think I will close this.

**Comment by taigrr** [comment]
Probably not. Having this issue here is probably breadcrumbs enough for anyone else who needs the info.

**Comment by taigrr** [comment]
No reason to reopen this, but I am adding to the 'breadcrumbs':

There are additional issues with using fin on a default arch installation, due to the assumptions it makes about your system.

As mentioned earlier, `startx` handles a ton of things for you that bash --login doesn't help with.

 - Be sure your XDG variables are set, such as `export XDG_RUNTIME_DIR=/run/user/$(id -u)` towards the top of your `.xinitrc`. Failing to do so breaks dbus and as a result, systemctl in user mode.
 - Make sure your user is in the `audio` group. Strangely, this isn't necessary when using `startx`.
 - Don't use `pulseaudio --start` in your `.xinitrc`. That was a red herring.

**Comment by taigrr** [comment]
#4 will close this issue.
