### ISSUE TITLE
Use Go's built-in embed package instead of fyne's

### ISSUE THREAD

**Issue by taigrr** [FyshOS/fin#7]
Fyne's generator for creating embedded static resources was a great idea, and necessary at the time of creation, but as of [Go 1.16](https://go.dev/doc/go1.16), there's a new standard library API called [embed](https://pkg.go.dev/embed).

I would like to propose fin moves over to that package instead. Benefits include:

- no inclusion of gigantic `.go` files in the workspace that editors can choke one when evaluating
- the original file can be included in the repo only once
- no need for go generate functions

I've already implemented this myself, PR incoming.

**Comment by taigrr** [comment]
This can't be done until Debian Stable includes go 1.16 support to ensure compatibility with FyshOS. The linked PR is closed to avoid clutter, but I will leave this issue open as a reminder when the time comes.

**Comment by taigrr** [comment]
It's here! [Golang v1.19 is now part of debian stable.](https://packages.debian.org/bookworm/golang/golang-1.19)

**Comment by taigrr** [comment]
PR updated in #8

**Comment by andydotxyz** [comment]
Yes this is good news. However I'd recommend holding back until Fyne updates to 1.17 minimum (on develop, will be 2.4.0) - just to avoid surprising developers?

**Comment by taigrr** [comment]
Yeah that makes sense.
